<?xml version="1.0" ?>
<testsuite errors="2" failures="2" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="2" time="287.40397548675537">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:4,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-01_18-51-41/test_1" time="177.5560212135315">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 391, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 36, 41, 45] or flex query and gsi query results not matching: [3, 4, 6, 7, 8, 16, 17, 18, 31, 32, 35, 37, 43, 57, 58, 59, 60]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:4,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-01_18-51-41/test_2" time="109.84795427322388">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 391, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 36, 41, 45] or flex query and gsi query results not matching: [3, 4, 6, 7, 8, 16, 17, 18, 31, 32, 35, 37, 43, 57, 58, 59, 60]\n']</error>
	</testcase>
</testsuite>
